### PR TITLE
Added all the supported resolution in the quick menu, not  just the two maximum resolutions 

### PR DESCRIPTION
**Pull request by dark-eye**
- added backend support to get the supported resolutions from the camera ( issue #13 )
- modifyed the UI to display the megapixels instead of the aspect ratio (as you can see the aspect ratio in the optin meny and by the size of the viewfinder)

### CODE REVIEW

**Comment by nfsprodriver** [comment]
On my hammerhead, list is resolutions is so long, that I can't move to upper one and select it. Can you make the list scrollable? Thanks!

**Comment by dark-eye** [comment]
Will do, however that rasies a UX issue  maybe we need a solution that will limit the list to some size prioritizing the common resolusion?

**Comment by Flohack74** [comment]
Why this PR shows clock-app in the title :P

**Comment by dark-eye** [comment]
Lol oops i guess i didn't slept enough lately my mistake

**Comment by Flohack74** [comment]
Can you make us a test click build? Would be great to see how it looks on other devices ;)

**Comment by dark-eye** [comment]
Took me a while  but i changed the quick options to be  scrollable.

Also here is armhf click : [com.ubuntu.camera_3.0.0.737_armhf.click](https://my.owndrive.com/index.php/s/1zUn6kkX4Yv65QZ)

**Comment by dark-eye** [comment]
@Flohack74 I only tested it on the meizu pro 5 but since the changes are in the QCamera level it *should* work for all of them... 
(Also is there an issue with my click package do you want me to provide a different configuration/architecture? )

**Comment by Flohack74** [comment]
@dark-eye Sorry forgot that you sent already a click :) - I installed on N5 now, however, switching the resolution lets the camera freeze. This could be N5-specific, but still we cant push an update with this bug.

BR

**Comment by dark-eye** [comment]
@Flohack74  Any chance you can send the logs?

**Comment by Flohack74** [comment]
http://paste.ubuntu.com/25334323/ but its not so helpful maybe. Switched resolution after taking 1 picture. Btw lots of qml errors, could be fixed.

**Comment by Flohack74** [comment]
Ok interesting thing, all 4:3 resolutions are OK and I can switch between them. However I can´t switch to the only 16:9 resolution I got on N5...

**Comment by dark-eye** [comment]
Hmm weird is that the case in the old build too? 
I`m working on decreasing the errors one at the time during the implementation/fixes of other issues, but you know what i`ll create an issue about it and do a fix session...

**Comment by Flohack74** [comment]
Cant tell you, there I got only 1 entry on the N5...
I sent out the click to other testers, if it is only on the N5 then I merge it. And we open a ticket for it. Its the same when you switch from photo to video mode, there it also gets stuck...

**Comment by Flohack74** [comment]
On the E5:
grafik
These are results from all possible solutions. Sorry to say but they are now too small =) => the list of resolutions is very device dependent and Im afraid this can be a real mess with more devices coming...

**Comment by dark-eye** [comment]
Hmm this is weird by the code you should now have the maximum resolution available in the old code down to the minimum supported resolution.

**Comment by Flohack74** [comment]
Maximum I got as 2MP, the E5 has 18MP or so ;) => I suggest we wait for further feedback...

**Comment by dark-eye** [comment]
Oh! did you try scrolling?

**Comment by Flohack74** [comment]
WAIT! IT CAN SCROLL???

**Comment by Flohack74** [comment]
Works!
So only the sorting of the list is weird, on the N5 its opposite to the E5... can we manually sort it?
image20170818_195334323

**Comment by dark-eye** [comment]
Sure will do i'll also add scrolling hints

**Comment by Flohack74** [comment]
Ok then its good for approval ;)

**Pull request merged**
