### PR TITLE
Update the term in ViewFinderOverlay.qml

### PR DESCRIPTION
**Pull request by Cypresslin**
As this app will run on a tablet as well, using the term "device" might be more appropriate

### CODE REVIEW

**Comment by NeoTheThird** [comment]
@dark-eye Do you want to merge PRs yourself here? Then i will un-watch the repo

**Comment by Flohack74** [comment]
Please note that any change to a translation requires also the pot file to be regenerated. This should be done by the app maintainer probably. Then commit the .pot file ONLY! Never check in po files, as this will break Weblate. Then, weblate will pick up the change, offer a new translations and people will hopefully supply it. After 1-2 weeks this will be returned with a commit of new po files.

**Comment by dark-eye** [comment]
Sorry it took me along time to respond was way from a computer for some time... :/

**Comment by dark-eye** [comment]
@Flohack74 Yes of course, I`ll talk with Brain i can't really upload the camera to the openstore as it has none regular permissions...

**Pull request merged**
