### PR TITLE
 Camera App #49 : Fix for different sizes to date stamp 

### PR DESCRIPTION
**Pull request by dark-eye**
- Also increased version number and hide the version from the information pager until a better version tacking/integration solution  will exists.

### CODE REVIEW

**Comment by Flohack74** [comment]
@dark-eye BTW I fixed now the automated Jenkins build :) That however means you need to sync version numbers between debian/changelog and manifest.json

**Comment by dark-eye** [comment]
@flohack74 will do I'll work on it tonight

**Comment by dark-eye** [comment]
@Flohack74 does the changelog created automagically by the build process or should i update it manually? if it is update by magic can you tell what tool is used?

**Comment by Flohack74** [comment]
No sorry, the debian changelog file needs to be edited manually :) - but there is a tool called debchange to help you with that.

**Pull request merged**
