### PR TITLE
Photo roll UI improvments

### PR DESCRIPTION
**Pull request by dark-eye**
Improved the Photo roll UI a little : 
- Implemented Camera App #35 Adjustable thumbnails in photo roll.
- Improved the grid to single photo transition
- Added bottom edge action to go back from single photo to photo roll
- Blurred the background of the header
- Removed the gallery app link in single photo to avoid confusion.

Also changed the maintainer to point to Ubports.

### CODE REVIEW

**Comment by sverzegnassi** [comment]
Cool, will have a look later tonight. At a first sight the code looks okay, so great job!

**Comment by sverzegnassi** [comment]
The resizeable thumbnails in the photo roll are amazing! I really like how you use the pinch-to-zoom gesture there. Well done!

On a sidenote, I'm not totally sure about the navigation flow. It seems a bit unnatural to perform a swipe from the bottom in order to return to the grid mode of the photo roll.

I'd suggest the following changes:
- Always show the link to gallery-app (even in the grid-based photo roll), but we move the action in the contextual menu in the header (in order to solve the ambiguity with similar icons)
- Remove the bottom edge action, as it performs the same action as the view mode toggle in the header

Thank for the PR. Again, great work!

P.S. I compared our photo roll with the one provided by the camera app on Android and iOS.
I see those apps only offer the slideshow, and rely on the gallery app for providing the grid overview of the shot pictures. We might want to align to this pattern in future, but it's preferable to defer such decision until we manage to get some UI designer on board :)

**Comment by dark-eye** [comment]
Hey @sverzegnassi,

I Moved the gallery app link to be in the contextual menu (though that kinda kills the idea of 'quick' access) i do agree that  we might need the gird view  to simply be the  gallery app however UT app start up is slow right now so i suggest to wait and see how  qt 5.9  improve it.

About the bottom edge, it was added as i noticed that navigating  through the photos i cumbersome with just the header button to switch between the photo roll and the  single photo view, and using a pinch out  to get back (like in android) require to fingers which means two handed use i just  thought  hey theres no bottom edge  in this part and ubuntu touch is all about it`s bottom edge  so i implemented  using bottom edge I suggest that you`ll test it a little and then go back you`ll feel the difference.

**Comment by sverzegnassi** [comment]
Yeah, my concern is that the two modes of the photo roll were meant to be alternative one to the other, but the UI hasn't been designed to make it clear (I point the finger at the previous maintainers at big-C).

Instead, the horizontal listview appears to be like a single photo view, rather than an alternative layout like it was meant to be (in the screenshot below, Google Camera make a good job in highlighting the swipeable nature of the view).

Adding the bottom edge to return at the grid mode suggests me that we go for the single photo view. At that point, the grid/slideshow toggle appears a bit redundant.

Anyway, this is not a reason for blocking the PR. If you feel it's okay, we can push it as-is into master.

As for the gallery-app link, it's still quicker than opening gallery-app from scopes, but we might prefer to highlight the nature of secondary action. :-)

[screenshot_20171207-145138](https://user-images.githubusercontent.com/1218443/33718609-4df04c8e-db5e-11e7-812f-0d36ab3f80b4.png)

**Comment by sverzegnassi** [comment]
Yes. As a last note, I'm not totally convinced by the new bottom edge, but the feeling is that it's rather the rest of the UI to be unclear or misbehaving.

In the longer term, but it's not related to this PR specifically, it might be preferable to remove the "About" pages from core apps. It's always a problem to keep the information updated, and hard-coding the version number into an app view isn't generally a good idea.

**Pull request merged**
