### PR TITLE
Issue #53 : Added customizable datestamp

### PR DESCRIPTION
**Pull request by dark-eye**
- Added customization of the datestamp color,position,opacity,format
-  Prevented siwping to photo roll while full page about/advanced options are displayed ( as this was triggered unintentionally quite a lot )

### CODE REVIEW

**Comment by Flohack74** [comment]
Is this more or less finished? =) Make a click and send it to QA group then

**Comment by dark-eye** [comment]
You can download the armhf click from [here](https://my.owndrive.com/index.php/s/TOS52xZLkPJiWoR)

**Comment by Flohack74** [comment]
Is this 15.04 build or 16.04?

**Comment by dark-eye** [comment]
15.04 for now...
Updated  [click](https://my.owndrive.com/index.php/s/0ps22QWG4w9Tx8Z) for testing.

**Comment by Flohack74** [comment]
Can you please post the click to the QA group and ping them for testing?

**Comment by dark-eye** [comment]
Did  some UI algments so here is  a new [version](https://my.owndrive.com/index.php/s/miYF6l3wDqPMteU)

**Comment by dark-eye** [comment]
updated 15.04 click can be found  [here](https://my.owndrive.com/index.php/s/wb8MACZaOX8bEIm)

**Comment by dark-eye** [comment]
Hmmm.... Any chance it`s ok to merge this PR? :)

**Pull request merged**
